substitutions:
  _IMAGE: 'frontend-prod/latest'
  _REGION: 'asia-northeast1'
  _SERVICE: 'reading-record-frontend'
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '$_REGION-docker.pkg.dev/${PROJECT_ID}/$_IMAGE', '-f', './deploy.Dockerfile', '.' ]
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_REGION-docker.pkg.dev/${PROJECT_ID}/$_IMAGE']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: 
    - -c
    - |
      gcloud run deploy ${_SERVICE} \
        --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_IMAGE} \
        --project ${PROJECT_ID} \
        --platform managed \
        --region ${_REGION} \
        --allow-unauthenticated \
        --update-env-vars="BASE_API_URL=$$BASE_API_URL"
  secretEnv: [ 'BASE_API_URL' ]
availableSecrets:
  secretManager:
    - versionName: "projects/${PROJECT_ID}/secrets/BASE_API_URL/versions/latest"
      env: BASE_API_URL
