version: "3.9"
services:
  backend:
    build: ./api_server
    volumes:
      - ./api_server:/api_server
    ports:
      - 8000:1234
    tty: true
    stdin_open: true
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.28
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reading_records
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql:/var/lib/mysql
