openapi: 3.0.0
info:
  title: Reading Records Controller Schema
  version: 1.0.0
paths:
  /readingRecords:
    post:
      operationId: createReadingRecords
      description: 読書記録の作成
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateReadingRecordDto'
      responses:
        '201':
          description: 読書記録の作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateReadingRecordResponseDto'
        '400':
          description: バリデーションエラー
          content:
            application/json:
              schema:
                description: バリデーションエラー
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: array
                    items:
                      description: TODO取得時のレスポンスのDTO
                      type: string
                  error:
                    type: string
                required:
                  - statusCode
                  - message
                  - error
        '401':
          description: 認証エラー
          content:
            application/json:
              schema:
                description: 認証エラー
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                required:
                  - statusCode
                  - message
    get:
      operationId: fetchAllReadingRecords
      description: 読書記録の一覧取得
      parameters: []
      responses:
        '200':
          description: 読書記録の一覧取得成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FetchAllReadingRecordResponseDto'
        '400':
          description: バリデーションエラー
          content:
            application/json:
              schema:
                description: バリデーションエラー
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: array
                    items:
                      description: TODO取得時のレスポンスのDTO
                      type: string
                  error:
                    type: string
                required:
                  - statusCode
                  - message
                  - error
        '401':
          description: 認証エラー
          content:
            application/json:
              schema:
                description: 認証エラー
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                required:
                  - statusCode
                  - message
        '404':
          description: Not Foundエラー
          content:
            application/json:
              schema:
                description: Not Foundエラー
                type: object
                properties:
                  statusCode:
                    type: number
                  message:
                    type: string
                required:
                  - statusCode
                  - message
components:
  schemas:
    ReadingRecordDto:
      description: 読書記録のDTO
      type: object
      properties:
        title:
          type: string
        learnedContent:
          type: string
          nullable: true
        impression:
          type: string
          nullable: true
      required:
        - title
        - learnedContent
        - impression
    CreateReadingRecordDto:
      description: 読書記録作成のrequest DTO
      type: object
      properties:
        title:
          type: string
        learnedContent:
          type: string
          nullable: true
        impression:
          type: string
          nullable: true
      required:
        - title
    CreateReadingRecordResponseDto:
      description: 読書記録の作成のレスポンスDTO
      type: object
      properties:
        readingRecord:
          description: 読書記録のDTO
          type: object
          properties:
            title:
              type: string
            learnedContent:
              type: string
              nullable: true
            impression:
              type: string
              nullable: true
          required:
            - title
            - learnedContent
            - impression
      required:
        - readingRecord
    FetchAllReadingRecordResponseDto:
      description: 読書記録の作成のレスポンスDTO
      type: array
      items:
        description: 読書記録のDTO
        type: object
        properties:
          title:
            type: string
          learnedContent:
            type: string
            nullable: true
          impression:
            type: string
            nullable: true
        required:
          - title
          - learnedContent
          - impression
