import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../../globals.css';
import { SignUpProvider } from './_contexts/SignUpContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Reading Record SignUp',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <SignUpProvider>
        <body className={inter.className}>{children}</body>
      </SignUpProvider>
    </html>
  );
}
