substitutions:
  _IMAGE: 'api-server-prod/latest'
  _REGION: 'asia-northeast1'
  _SERVICE: 'reading-record'
  _SECRETS: 'DATABASE_URL=DATABASE_URL:latest,BOOKS_API_ENDPOINT=BOOKS_API_ENDPOINT:latest,BOOKS_API_APPLICATION_ID=BOOKS_API_APPLICATION_ID:latest,GCS_KEY_FILE_PATH=GCS_KEY_FILE_PATH:latest,BUCKET_NAME=BUCKET_NAME:latest'
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '$_REGION-docker.pkg.dev/${PROJECT_ID}/$_IMAGE', '-f', './deploy.Dockerfile', '.' ]
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_REGION-docker.pkg.dev/${PROJECT_ID}/$_IMAGE']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'jobs'
  - 'deploy'
  - '$_SERVICE'
  - '--image'
  - '$_REGION-docker.pkg.dev/${PROJECT_ID}/$_IMAGE'
  - '--region'
  - '$_REGION'
  - '--set-secrets'
  - '$_SECRETS'
  - '--execute-now'
images:
- 'asia-northeast1-docker.pkg.dev/reading-record-425713/api-server-prod/latest:latest'
